language: python


stages:
# Testing stage for all commits on all branches except tags
  - name: test
# Pypi deploy if tagged
  - name: pypi_deploy
    if: tag =~ ^\d+\.\d+\.\d+$
# Anaconda deploy if tagged and deployed to pypi
  - name: anaconda_deploy
    if: tag =~ ^\d+\.\d+\.\d+$


install:
    - pip install coverage flake8 twine


jobs:
  include:
    # ---------------------------------------------------------------------------------
    # Test, done on 3.5, 3.6, and 3.7
    # Python 3.5
    - stage: test
      script:
        - python --version
        - python setup.py install
        - coverage run --rcfile coverage.cfg setup.py test
        - coverage report -m
        - flake8
      python:
        - 3.5
    # Python 3.6
    - stage: test
      script:
        - python --version
        - python setup.py install
        - coverage run --rcfile coverage.cfg setup.py test
        - coverage report -m
        - flake8
      python:
        - 3.6
    # Python 3.7 - Use workaround to get 3.7 to work - https://github.com/travis-ci/travis-ci/issues/9815
    - stage: test
      script:
        - python --version
        - python setup.py install
        - coverage run --rcfile coverage.cfg setup.py test
        - coverage report -m
        - flake8
      python:
        - 3.7
      dist: xenial
      sudo: true

    # ---------------------------------------------------------------------------------
    # Pypi Deploy
    - stage: pypi_deploy
      script:
        - export SETUP_VERSION=$(python ./setup.py --version)
        - if [ $SETUP_VERSION == $TRAVIS_BRANCH ]; then echo "Versions match..."; else echo "Version in setup does not match tag" && sleep 5 && exit 1; fi
        - python setup.py sdist
        - twine upload -u $PIP_USERNAME -p $PIP_PASSWORD dist/*
      python:
        - 3.6

    # ---------------------------------------------------------------------------------
    # Anaconda Deploy
    - stage: anaconda_deploy
      script:
        - echo "Installing a fresh version of Miniconda."
        - curl -L https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh > ~/miniconda.sh;
        - bash ~/miniconda.sh -b -p ~/miniconda
        - source ~/miniconda/bin/activate root
        # Configure conda.
        - echo "Configuring conda."
        - conda config --add channels tethysplatform
        - conda config --append channels conda-forge
        - conda config --set show_channel_urls true
        - conda install --yes --quiet networkx conda-build jinja2 anaconda-client
        # We just want to build all of the recipes.
        - conda build ./conda_recipe --token ${CI_CONDA_TOKEN_SECRET}
      python:
        - 3.6

